miniblog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=150)
  desc = models.TextField()

class contact(models.Model):
  name = models.CharField(max_length=30)
  email = models.CharField(max_length=40)
  address = models.CharField(max_length=30)
  message = models.CharField(max_length=150)

miniblog/blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages
import time
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group
from blog.form import user_form, blog_form, contact_form
from .models import Post, contact

# Create your views here.

# home: 
def home(request):
    posts = Post.objects.all()
    return render(request, "blog/home.html", {'posts': posts})

# about:
def about(request):
    return render(request, "blog/about.html")

# Dashboard
def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()  
        user = request.user
        full_name = user.get_full_name()
        gps = user.groups.all()
        return render(request, "blog/dashboard.html", {'stub': posts, 'full_name': full_name, 'groups': gps})
    else:
        return HttpResponseRedirect('/login/')

# Login:
def user_login(request):
    if not request.user.is_authenticated:
      if request.method == 'POST':
          fm =AuthenticationForm(request=request, data=request.POST)
          if fm.is_valid():
              uname = fm.cleaned_data['username']
              upass = fm.cleaned_data['password']
              user = authenticate(username=uname, password=upass)
              if user is not None:
                  login(request, user)
                  messages.success(request, 'Logged In!!')
                  return HttpResponseRedirect('/dashboard/')
              
      else:
          fm = AuthenticationForm()
      return render(request, 'blog/login.html', {'form': fm})
    else:
        return HttpResponseRedirect('/dashboard/')

# Signup:
def user_signup(request):
    if request.method == 'POST':
        fm = user_form(request.POST)
        if fm.is_valid():
            user = fm.save()
            group = Group.objects.get(name="Author")
            user.groups.add(group)
            return HttpResponseRedirect('/login/')

    else:
        fm = user_form()
    return render(request, "blog/signup.html", {'form': fm})

# contact:
def contact(request): 
    if request.method == 'POST':
        nm = request.POST['name']
        em = request.POST['email']
        ad = request.POST['address']
        msg = request.POST['message']
        contact.objects.create(name=nm, email=em, address=ad, message=msg)
        return HttpResponseRedirect('/')
    return render(request, "blog/contact.html")

# logout:
def user_logout(request):
        logout(request)
        return HttpResponseRedirect('/login/')

# delete:
def delete_data(request, id):
    if request.user.is_authenticated:
      if request.method == "POST":
         pi = Post.objects.get(pk=id)
         pi.delete()
         return HttpResponseRedirect('/dashboard/')
    else:
      return HttpResponseRedirect('/login/')

# update:   
def update_data(request, id):
   if request.user.is_authenticated:
      if request.method == 'POST':
        pi = Post.objects.get(pk=id)
        fm = blog_form(request.POST, instance=pi)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect('/')
      else:
        pi = Post.objects.get(pk=id)
        fm = blog_form(instance=pi)
      return render(request, 'blog/edit.html', {'form':fm})
   else:
      return HttpResponseRedirect('/login/')
   
# posting:
def posting(request):
    if request.user.is_authenticated:
      if request.method == 'POST':
          fm =blog_form(request.POST)
          if fm.is_valid():
             fm.save()
             return HttpResponseRedirect("/dashboard/")
      else:    
       fm = blog_form()
      return render(request, 'blog/posting.html', {'form':fm})
    else:
        return HttpResponseRedirect('/login/')
    
# Reading:
def read_data(request, id):
        ds = Post.objects.get(pk=id)
        return render(request, 'blog/display.html', {'data': ds})







miniblog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-10">
       <h3 class="my-5 alert alert-info">About page</h3>
       <p>I am Brijesh kumar, here is my resume.</p>
       <img src={% static 'blog/images/me.jpg' %} width="800" height="1080" alt="jpg">
    </div>
{% endblock %}

miniblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "blog/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">
    <title>Miniblog</title>
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include "blog/navbar.html" %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}

        </div>
    </div>
</body>
</html>

miniblog/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-10">
        <h3 class="mt-5 alert alert-info">Contact Us</h3>
        <form action="{% url 'contacts' %}" method="post">
            
            <div class="form-row">
                {% csrf_token %}
                <div class="form-group col-md-6">
                    <label for="inputname">Name</label>
                    <input type="text" class="form-control" name="name" id="inputName">
                </div>
                
                <div class="form-group col-md-6">
                    <label for="inputEmail">Email</label>
                    <input type="email" class="form-control" name="email" id="inputEmail">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputaddress">Address</label>
                    <input type="text" class="form-control" name="address" id="inputaddress">
                </div>
                <div class="form-group col-md-6">
                    <label for="message">Message</label>
                    <textarea class="form-control" name="message" id="message" row="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">send</button>
            </div>   
        </form>
    </div>
{% endblock %}

miniblog/blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}

{% block side %}
<div class='col-sm-2 text-white my-2 text-center'>
  <h4 class="my-2">Profile</h4>
  <h5>{{full_name}}</h5>
  {% for group in groups %}
    <p>{{group.name}}</p>
  {% endfor %}
</div>
{% endblock side %}


{% block content %}
    <div class="col-sm-10">
       <h3 class="my-2 alert alert-info">Dashboard</h3>
            <a href="{% url "newpost" %}" class=" btn btn-success">write post</a>
            <h4 class=" my-2 text-center alert alert-warning">Show Post Information</h4>
            {% if stub %}
            <table class="table table table-hover">
                    <thead>
                      <tr>
                        <th scope="blog" class='table-info'>BLOGS</th>
                        <th scope="description" class='table-info'>Descriptions</th>
                        <th scope="action" class='table-info'>ACTIONS</th>
                      </tr>
                    </thead>
                    <tbody>
                     {% for s in stub  %}
                      <tr>
                        <td>{{s.title}}</td>
                        <td>{{s.desc}}</td>
                        <td>
                            <form action="{% url "updatedata" s.id %}" method="post"  class="d-inline">
                                {% csrf_token %}
                                <input type="submit" class=" mx-2 btn btn-warning" value="Edit">
                              </form>
                            {% if perms.blog.delete_post %}
                              <form action="{% url "deletedata" s.id %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" value="delete">
                              </form>
                            {% endif %}
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
            </table>
            {% else %}
            <h4 class="text-center alert alert-danger">No Data</h4>
            {% endif %}
    
        </div>
    </div>
</div>
{% endblock %}

miniblog/blog/templates/blog/display.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
  <div class="col-sm-10">
    <h3 class="my-5 text-center alert alert-info">Blog</h3>
        <div class="p-2 mb-2 rounded-2   bg -dark bg-gradient">
          <div class="container-fluid py-2">
            <h1 class="display-10 fw-sm">{{ data.title }}</h1>
            <p class="col-md-15 fs-5">{{ data.desc }}</p>
          </div>
          <a href="{% url 'home' %}" class="btn btn-info">Back</a>
        </div>
  </div>
{% endblock content %}

miniblog/blog/templates/blog/edit.html
{% extends "blog/base.html" %}   
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">New Post</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Update">
        <a href="{% url 'dashboard' %}" class='btn btn-danger'>Cancel</a>
    </form>
</div>
{% endblock content %}

miniblog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
  <div class="col-sm-10">
    <h3 class="my-5 alert alert-info">Home Page</h3>
    {% if posts %}
     {% for post in posts %}
       <div class="p-2 mb-2 rounded-2  bg-gradient">
         <div class="container-fluid py-2">
           <h1 class="display-10 fw-sm">{{ post.title }}</h1>
           <form action="{% url 'readdata' post.id %}" method="post"  class="d-inline">
            {% csrf_token %}
            <input type="submit" class=" mx-2 btn btn-primary" value="Read">
          </form>
           
         </div>
       </div>
     {% endfor %}
    {% else %}
     <h4 class="text-center alert alert-warning">No Posts Available</h4>
    {% endif %}
  </div>
{% endblock %}

miniblog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-10">
       <h3 class="my-5 alert alert-info">Login</h3>
       <form action="" method="post">
        {% csrf_token %}
        {% for fm in form  %}
         <div class="form-group">
            {{fm.label_tag}} {{fm}}<small class="text-warning"> {{fm.errors|striptags}}</small>
         </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Login">
        {% if fm.non_field_errors %}
            {% for error in fm.non_field_errors  %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
        {% endif %}
       </form>
      
    </div>
{% endblock %}

miniblog/blog/templates/blog/logout.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-10">
       <h3 class="my-5 alert alert-info">Logout page</h3>
       <p>Do u want to logout</p>
       <form action="" method="post">
       <input  class="text-bg-danger" href="{% url "logout" %}" type="button" value="Confirm">
       </form>
    </div>
{% endblock %}

miniblog/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'about' %}">MiniBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>    
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacts' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>

        
      </ul>
    </div>
  </div>
</nav>

miniblog/blog/templates/blog/posting.html
{% extends "blog/base.html" %}   
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">New Post</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="submit">
        <a href="{% url 'dashboard' %}" class='btn btn-danger'>Cancel</a>
    </form>
</div>
{% endblock content %}

miniblog/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-sm-10">
        <h4  class="alert alert-info my-5">Became an Author</h4>
        <form action="" method="post">
         {% csrf_token %}
         {% for fm in form  %}
          <div class="form-group">
            {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
          </div>
         {% endfor %}
         <input type="submit" class="btn btn-primary" value="Signup">
         {% if fm.non_field_errors %}
            {% for error in fm.non_field_errors  %}
             <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
         {% endif %}
       </form>
      
    </div>
</div>
{% endblock %}